//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Settings/InputActions/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/InputActions/PlayerControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""GyroDrawing"",
            ""id"": ""7a03a09b-7af1-4a41-8398-0d785ddf5737"",
            ""actions"": [
                {
                    ""name"": ""DeviceRotation"",
                    ""type"": ""Value"",
                    ""id"": ""762c0e24-20f4-4da8-9853-8e67167dc32d"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DeviceTilt"",
                    ""type"": ""Value"",
                    ""id"": ""092ff787-3a3c-412f-8240-dd9c5db48de5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TiltSensitivity"",
                    ""type"": ""Value"",
                    ""id"": ""4ce7e277-a4c2-4d09-841d-0fd830d9c961"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Scale(factor=2),AxisDeadzone(min=0.5,max=5)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7d749565-bdf4-4a78-9548-7c257da1dd9e"",
                    ""path"": ""<AttitudeSensor>/attitude"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f96ff17-95ca-4bc3-ac77-53bc3ace64e3"",
                    ""path"": ""<Accelerometer>/acceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceTilt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b0a673ba-1948-48b1-8ac1-6fa031fac6ac"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeviceTilt"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0615b9ab-f0e1-4406-9d2c-3709a28326a1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0)"",
                    ""groups"": """",
                    ""action"": ""DeviceTilt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""243b2ad6-1bc3-431f-a750-91a372834a7e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0,y=-1)"",
                    ""groups"": """",
                    ""action"": ""DeviceTilt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""87305730-d1da-43a7-a70d-a466ba0ef489"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=-1,y=0)"",
                    ""groups"": """",
                    ""action"": ""DeviceTilt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""56dafeb0-6150-4b73-bba2-eca896de92b9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(y=0)"",
                    ""groups"": """",
                    ""action"": ""DeviceTilt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""38f0ce87-536f-4d7a-899b-05f50acceb03"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TiltSensitivity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TouchInteraction"",
            ""id"": ""23a3f100-fb67-4239-ad36-3d825e82a560"",
            ""actions"": [
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""Value"",
                    ""id"": ""211a2edf-519a-48d7-8bf6-0e44a16e00ab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchDelta"",
                    ""type"": ""Value"",
                    ""id"": ""5e13dc01-790e-466e-98ed-87fbbb64471a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryTouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ab5f9760-05dd-4154-a6e4-13837b5cd361"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPress"",
                    ""type"": ""Button"",
                    ""id"": ""29029a12-313e-480c-869f-7a7ae67faba6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""418d3535-c87b-403f-a39d-da3bd81a706e"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74716506-41de-4aff-a70c-730384c8a695"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08aa2719-4a5f-4a9b-9bfd-fd5b01641a38"",
                    ""path"": ""<Touchscreen>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77788d35-a16e-4f89-8a2f-3b7f558ecd88"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5c09dd3-ac56-40c8-a7bf-123f29d37113"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ff0643d-3ea2-408b-920a-3fdfa75b0958"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f65f6c11-8628-4e1e-be52-14fe27051bca"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GyroDrawing
        m_GyroDrawing = asset.FindActionMap("GyroDrawing", throwIfNotFound: true);
        m_GyroDrawing_DeviceRotation = m_GyroDrawing.FindAction("DeviceRotation", throwIfNotFound: true);
        m_GyroDrawing_DeviceTilt = m_GyroDrawing.FindAction("DeviceTilt", throwIfNotFound: true);
        m_GyroDrawing_TiltSensitivity = m_GyroDrawing.FindAction("TiltSensitivity", throwIfNotFound: true);
        // TouchInteraction
        m_TouchInteraction = asset.FindActionMap("TouchInteraction", throwIfNotFound: true);
        m_TouchInteraction_TouchPosition = m_TouchInteraction.FindAction("TouchPosition", throwIfNotFound: true);
        m_TouchInteraction_TouchDelta = m_TouchInteraction.FindAction("TouchDelta", throwIfNotFound: true);
        m_TouchInteraction_PrimaryTouch = m_TouchInteraction.FindAction("PrimaryTouch", throwIfNotFound: true);
        m_TouchInteraction_TouchPress = m_TouchInteraction.FindAction("TouchPress", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_GyroDrawing.enabled, "This will cause a leak and performance issues, PlayerControls.GyroDrawing.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TouchInteraction.enabled, "This will cause a leak and performance issues, PlayerControls.TouchInteraction.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GyroDrawing
    private readonly InputActionMap m_GyroDrawing;
    private List<IGyroDrawingActions> m_GyroDrawingActionsCallbackInterfaces = new List<IGyroDrawingActions>();
    private readonly InputAction m_GyroDrawing_DeviceRotation;
    private readonly InputAction m_GyroDrawing_DeviceTilt;
    private readonly InputAction m_GyroDrawing_TiltSensitivity;
    /// <summary>
    /// Provides access to input actions defined in input action map "GyroDrawing".
    /// </summary>
    public struct GyroDrawingActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GyroDrawingActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GyroDrawing/DeviceRotation".
        /// </summary>
        public InputAction @DeviceRotation => m_Wrapper.m_GyroDrawing_DeviceRotation;
        /// <summary>
        /// Provides access to the underlying input action "GyroDrawing/DeviceTilt".
        /// </summary>
        public InputAction @DeviceTilt => m_Wrapper.m_GyroDrawing_DeviceTilt;
        /// <summary>
        /// Provides access to the underlying input action "GyroDrawing/TiltSensitivity".
        /// </summary>
        public InputAction @TiltSensitivity => m_Wrapper.m_GyroDrawing_TiltSensitivity;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GyroDrawing; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GyroDrawingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GyroDrawingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GyroDrawingActions" />
        public void AddCallbacks(IGyroDrawingActions instance)
        {
            if (instance == null || m_Wrapper.m_GyroDrawingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GyroDrawingActionsCallbackInterfaces.Add(instance);
            @DeviceRotation.started += instance.OnDeviceRotation;
            @DeviceRotation.performed += instance.OnDeviceRotation;
            @DeviceRotation.canceled += instance.OnDeviceRotation;
            @DeviceTilt.started += instance.OnDeviceTilt;
            @DeviceTilt.performed += instance.OnDeviceTilt;
            @DeviceTilt.canceled += instance.OnDeviceTilt;
            @TiltSensitivity.started += instance.OnTiltSensitivity;
            @TiltSensitivity.performed += instance.OnTiltSensitivity;
            @TiltSensitivity.canceled += instance.OnTiltSensitivity;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GyroDrawingActions" />
        private void UnregisterCallbacks(IGyroDrawingActions instance)
        {
            @DeviceRotation.started -= instance.OnDeviceRotation;
            @DeviceRotation.performed -= instance.OnDeviceRotation;
            @DeviceRotation.canceled -= instance.OnDeviceRotation;
            @DeviceTilt.started -= instance.OnDeviceTilt;
            @DeviceTilt.performed -= instance.OnDeviceTilt;
            @DeviceTilt.canceled -= instance.OnDeviceTilt;
            @TiltSensitivity.started -= instance.OnTiltSensitivity;
            @TiltSensitivity.performed -= instance.OnTiltSensitivity;
            @TiltSensitivity.canceled -= instance.OnTiltSensitivity;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GyroDrawingActions.UnregisterCallbacks(IGyroDrawingActions)" />.
        /// </summary>
        /// <seealso cref="GyroDrawingActions.UnregisterCallbacks(IGyroDrawingActions)" />
        public void RemoveCallbacks(IGyroDrawingActions instance)
        {
            if (m_Wrapper.m_GyroDrawingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GyroDrawingActions.AddCallbacks(IGyroDrawingActions)" />
        /// <seealso cref="GyroDrawingActions.RemoveCallbacks(IGyroDrawingActions)" />
        /// <seealso cref="GyroDrawingActions.UnregisterCallbacks(IGyroDrawingActions)" />
        public void SetCallbacks(IGyroDrawingActions instance)
        {
            foreach (var item in m_Wrapper.m_GyroDrawingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GyroDrawingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GyroDrawingActions" /> instance referencing this action map.
    /// </summary>
    public GyroDrawingActions @GyroDrawing => new GyroDrawingActions(this);

    // TouchInteraction
    private readonly InputActionMap m_TouchInteraction;
    private List<ITouchInteractionActions> m_TouchInteractionActionsCallbackInterfaces = new List<ITouchInteractionActions>();
    private readonly InputAction m_TouchInteraction_TouchPosition;
    private readonly InputAction m_TouchInteraction_TouchDelta;
    private readonly InputAction m_TouchInteraction_PrimaryTouch;
    private readonly InputAction m_TouchInteraction_TouchPress;
    /// <summary>
    /// Provides access to input actions defined in input action map "TouchInteraction".
    /// </summary>
    public struct TouchInteractionActions
    {
        private @PlayerControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public TouchInteractionActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "TouchInteraction/TouchPosition".
        /// </summary>
        public InputAction @TouchPosition => m_Wrapper.m_TouchInteraction_TouchPosition;
        /// <summary>
        /// Provides access to the underlying input action "TouchInteraction/TouchDelta".
        /// </summary>
        public InputAction @TouchDelta => m_Wrapper.m_TouchInteraction_TouchDelta;
        /// <summary>
        /// Provides access to the underlying input action "TouchInteraction/PrimaryTouch".
        /// </summary>
        public InputAction @PrimaryTouch => m_Wrapper.m_TouchInteraction_PrimaryTouch;
        /// <summary>
        /// Provides access to the underlying input action "TouchInteraction/TouchPress".
        /// </summary>
        public InputAction @TouchPress => m_Wrapper.m_TouchInteraction_TouchPress;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_TouchInteraction; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="TouchInteractionActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(TouchInteractionActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="TouchInteractionActions" />
        public void AddCallbacks(ITouchInteractionActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchInteractionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchInteractionActionsCallbackInterfaces.Add(instance);
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @TouchDelta.started += instance.OnTouchDelta;
            @TouchDelta.performed += instance.OnTouchDelta;
            @TouchDelta.canceled += instance.OnTouchDelta;
            @PrimaryTouch.started += instance.OnPrimaryTouch;
            @PrimaryTouch.performed += instance.OnPrimaryTouch;
            @PrimaryTouch.canceled += instance.OnPrimaryTouch;
            @TouchPress.started += instance.OnTouchPress;
            @TouchPress.performed += instance.OnTouchPress;
            @TouchPress.canceled += instance.OnTouchPress;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="TouchInteractionActions" />
        private void UnregisterCallbacks(ITouchInteractionActions instance)
        {
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @TouchDelta.started -= instance.OnTouchDelta;
            @TouchDelta.performed -= instance.OnTouchDelta;
            @TouchDelta.canceled -= instance.OnTouchDelta;
            @PrimaryTouch.started -= instance.OnPrimaryTouch;
            @PrimaryTouch.performed -= instance.OnPrimaryTouch;
            @PrimaryTouch.canceled -= instance.OnPrimaryTouch;
            @TouchPress.started -= instance.OnTouchPress;
            @TouchPress.performed -= instance.OnTouchPress;
            @TouchPress.canceled -= instance.OnTouchPress;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TouchInteractionActions.UnregisterCallbacks(ITouchInteractionActions)" />.
        /// </summary>
        /// <seealso cref="TouchInteractionActions.UnregisterCallbacks(ITouchInteractionActions)" />
        public void RemoveCallbacks(ITouchInteractionActions instance)
        {
            if (m_Wrapper.m_TouchInteractionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="TouchInteractionActions.AddCallbacks(ITouchInteractionActions)" />
        /// <seealso cref="TouchInteractionActions.RemoveCallbacks(ITouchInteractionActions)" />
        /// <seealso cref="TouchInteractionActions.UnregisterCallbacks(ITouchInteractionActions)" />
        public void SetCallbacks(ITouchInteractionActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchInteractionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchInteractionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="TouchInteractionActions" /> instance referencing this action map.
    /// </summary>
    public TouchInteractionActions @TouchInteraction => new TouchInteractionActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GyroDrawing" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GyroDrawingActions.AddCallbacks(IGyroDrawingActions)" />
    /// <seealso cref="GyroDrawingActions.RemoveCallbacks(IGyroDrawingActions)" />
    public interface IGyroDrawingActions
    {
        /// <summary>
        /// Method invoked when associated input action "DeviceRotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDeviceRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DeviceTilt" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDeviceTilt(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TiltSensitivity" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTiltSensitivity(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "TouchInteraction" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="TouchInteractionActions.AddCallbacks(ITouchInteractionActions)" />
    /// <seealso cref="TouchInteractionActions.RemoveCallbacks(ITouchInteractionActions)" />
    public interface ITouchInteractionActions
    {
        /// <summary>
        /// Method invoked when associated input action "TouchPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchDelta" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchDelta(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrimaryTouch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryTouch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchPress" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPress(InputAction.CallbackContext context);
    }
}
